[package]
name = "hs-rs"
version = "0.1.0"
edition = "2018"
authors = ["Lictor <lctrgzmn@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "rusty"
crate-type = ["staticlib"]

[dependencies]

